[package]
name = "example_cli"
version = "2026.3.15"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.102"
axum = { version = "0.8", default-features = false }
clap = { version = "4.5.60", features = ["derive"] }
wasip2 = "1.0.2"
wit-bindgen = "0.53.1"
wstd = "0.6.6"
wstd-axum = "0.6.6"
